package com.nicovegasr.caesar

import com.facebook.react.BaseReactPackage
import com.facebook.react.bridge.NativeModule
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.module.model.ReactModuleInfoProvider

/**
 * Marker ReactPackage required by the RN CLI to consider this library a valid
 * Android dependency. The actual TurboModule (`CaesarTurboModule`) lives in C++
 * and is registered via the cxxModuleProvider generated by codegen from
 * `react-native.config.js` (`cxxModuleHeaderName`).
 */
class CaesarPackage : BaseReactPackage() {
  override fun getModule(name: String, reactContext: ReactApplicationContext): NativeModule? = null
  override fun getReactModuleInfoProvider(): ReactModuleInfoProvider =
    ReactModuleInfoProvider { emptyMap() }
}
